# M2#A29 - TDD - testando exceções

Vamos testar se o elemento passado não for um array ou seja quando ele passar um valor que não seja um array vamos dar um erro do tipo TypeError.


No primeiro vídeo que começamos a testar o próprio map vimos que o chai tem um método `throw` e como ele conseguimos testar o erro mais se tivermos mais do que uma verificação não conseguimos utilizar esse método, por quê esse método `throw` dispara o erro quando uma função é executada e você precisa passar esse método no expect do `chai` e não executá-la. 

No caso como queremos testar a execeção que é executar um método passando um valor diferente do que ele precisa nós devemos fazer o teste executando o `throw` do próprio javascript.

### Criando teste para mostrar o erro TypeError quando não for passado um array

#### `let error` 

Foi necessário declarar uma variável fora como undefined para termos um valor diferente do resultado esperado. 

Dessa forma conseguimos validar o teste atráves do método expect do chai pois como o valor ainda é undefined o teste espera o nosso tratamento dentro catch(e) com o valor igual a equal(). Então a variável error = e recebe o tratamento de catch(e)

```
it('map(1) should throw a TyperError', () => {
  let error 
  try {
    map(1)
  } catch (e) {
    error = e
  }

  expect(error.name).to.be.equal('TypeError')
})
```

### Criando e testando uma mensagem de erro customizada para o primeiro parâmetro caso ele não seja um array
```
it('map(1) should throw a TyperError with message "The first parameter must be an array"', () => {
  let error

  try {
    map(1)
  } catch (e) {
    error = e
  }

  expect(error.message).to.be.equal('The first parameter must be an array')
})
```

### Criando teste para mostrar o erro TypeError quando não for passado uma função no segundo parâmetro
```
it('map([1, 2], "function") should throw a TyperError ', () => {
  let error

  try {
    map([1, 2], 'function')
  } catch (e) {
    error = e
  }

  expect(error.name).to.be.equal('TypeError')
})
```

### Criando e testando uma mensagem de erro customizada para o segundo parâmetro caso ele não seja uma função
```
it('map([1, 2], "function") should throw a TyperError with message "The second parameter must be a function" ', () => {
  let error

  try {
    map([1, 2], 'function')
  } catch (e) {
    error = e
  }

  expect(error.message).to.be.equal('The second parameter must be a function')
})
```